[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
RData = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
