[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
RData = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
